import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ApolloProviderWrapper from "@/lib/ApolloProviderWrapper";
// import PbPageElementsProvider from "@/lib/PbPageElementsProvider";
import StoreProvider from "./StoreProvider";
import dynamic from "next/dynamic";
const PbPageElementsProvider = dynamic(() => import('@/lib/PbPageElementsProvider'), {ssr: false})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ApolloProviderWrapper>
            <PbPageElementsProvider>{children}</PbPageElementsProvider>
          </ApolloProviderWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
